### ISSUE TITLE
Error while retrieving entity resources.

### ISSUE THREAD

**Issue by shardnit** [lmcalpin/odata_provider_example_rb#1]
I have tried this sample rails app with the odata_server gem and it works fine. However, when I try to follow the same approach for my rails-api project, that needs to support OData format, I get the following the error (while rendering):
...
ActionView::Template::Error (undefined method `o_data_atom_feed' for #<#Class:0x007f8b8b7c2338:0x007f8b91050b08>):
...
I get this error when requesting an entity(/OData/<entity name>), irrespective of the format (xml or json).

**Comment by lmcalpin** [comment]
Did you mount the engine? 
The routes file in the example includes this line; it's necessary to make it work:
mount OData::Engine, :at => "/OData"

**Comment by shardnit** [comment]
Yes, I did. Enpoints like /OData and /OData/$metadata do work. But requesting an entity's data, for instance /OData/Contacts, throws an error (while rendering JSON/atom view).

**Comment by lmcalpin** [comment]
I'll need a full stack trace and either a unit test or an example project that I can run that replicates the issue, and then I will happily look into it.  I'd also welcome a pull request if you figure it out yourself.

**Comment by j0-1** [comment]
I hit this issue when using a fork of the odata_server engine, and tracked it back to Helpers not being loaded.  With a rails-api app the helpers aren't automatically loaded so you need to:

```
include ActionController::Helpers
```

in your ApplicationController that will be derived from ActionController::API in a rails-api app.

**Comment by lmcalpin** [comment]
Thanks for the info. I wasn't familiar with rails-api.  I believe the example should work with that now.
